In [115]:
import numpy as np

def binSplitDataSet(dataSet, feature, val):
    mat0 = dataSet[np.nonzero(dataSet[:,feature] > val)[0],:][0]
    mat1 = dataSet[np.nonzero(dataSet[:,feature] <= val)[0],:][0]
    return mat0, mat1


In [116]:
testMat = np.mat(np.eye(4))
print(testMat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [117]:
dataSet = np.random.randn(100,2)
#print(dataSet)

In [118]:
def regLeaf(dataSet):
    return np.mean(dataSet[:,-1])

In [119]:
def regErr(dataSet):
    return np.var(dataSet[:,-1]) * np.shape(dataSet)[0]


In [123]:
def chooseBestSplit(dataSet, leafType=regLeaf, errType=regErr, ops=(1,4)):
    tolS = ops[0]
    tolN = ops[1]
    if len(set(dataSet[:,-1].T.tolist())) == 1:
        return None, leafType(dataSet)
    
    m,n = np.shape(dataSet)
    S = errType(dataSet)
    bestS = np.Inf; bestIndex = 0; bestValue = 0
    for featIndex in range(n-1):
        print("featindex:",featIndex)
        for splitVal in set(dataSet[:, featIndex]):
            mat0, mat1 = binSplitDataSet(dataSet, featIndex, splitVal)
            print("mat0:",mat0)
            print("mat1",mat1)
            if ((np.shape(mat0)[0] < tolN) or (np.shape(mat1)[0] < tolN)):
                continue
            newS = errType(mat0) + errType(mat1)
            if newS < bestS:
                bestIndex = featIndex
                bestValue = splitVal
                bestS = newS
    if (S-bestS) < tolS:
        return None, leafType(dataSet)
    mat0, mat1 = binSplitDataSet(dataSet, bestIndex, bestValue)
    if ((np.shape(mat0)[0] < tolN) or (np.shape(mat1)[0] < tolN)):
        return None, leafType(dataSet)
    return bestIndex, bestValue
    
        

In [124]:
res = chooseBestSplit(dataSet)

featindex: 0
mat0: [0.44183808 0.39253272]
mat1 [-0.61964314 -0.5639533 ]
mat0: [-0.61964314 -0.5639533 ]
mat1 [-0.75885794 -0.33554926]
mat0: [0.83512922 0.89576702]
mat1 [-0.61964314 -0.5639533 ]
mat0: [ 0.41604908 -0.20217097]
mat1 [-0.61964314 -0.5639533 ]
mat0: [ 0.41604908 -0.20217097]
mat1 [-0.61964314 -0.5639533 ]
mat0: [ 1.66863741 -0.88660818]
mat1 [-0.61964314 -0.5639533 ]
mat0: [2.87582546 2.41157744]
mat1 [-0.61964314 -0.5639533 ]
mat0: [ 0.41604908 -0.20217097]
mat1 [-0.61964314 -0.5639533 ]
mat0: [-0.61964314 -0.5639533 ]
mat1 [-1.2411994   0.30852827]
mat0: [0.83512922 0.89576702]
mat1 [-0.61964314 -0.5639533 ]
mat0: [ 1.66863741 -0.88660818]
mat1 [-0.61964314 -0.5639533 ]


IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
res

-0.6273008521776904
